language: ruby
os: linux

rvm:
  - 2.4

env:
  global:
    - NOW_SCRIPT="../node_modules/.bin/now"
    - NOW_FLAGS="-A ../package.json --token ${NOW_TOKEN}"

install:
  - bundle install --jobs=3 --retry=3
  - npm install

script:
  - bundle exec jekyll build
  - |
    cd _site/
    $NOW_SCRIPT --public $NOW_FLAGS
    $NOW_SCRIPT alias $NOW_FLAGS
    $NOW_SCRIPT rm baptiste-leduc $NOW_FLAGS -s -y
    cd -

cache:
  bundler: true
  directories:
    - /home/travis/.rvm/