# Site Info
title:              "Baptiste Leduc"
description:        "About me & some blog posts"

# Author Info
author_name:        "Baptiste Leduc"
author_email:       baptiste.leduc@gmail.com
author_gravatar:    369bc00f6a4b6d8d8b7d82df901009c2
twitter_username:   MrFatPanda123
github_username:    Korbeil
spotify_user:       11130977231

# Google APIs
google_verify:      HHnf5ZHystzxEmh_821fA6cPVYxp24g00G92h8KUDN8
google_analytics:   UA-118536100-1

# Site Settings
url:                "https://baptiste-leduc.now.sh"
baseurl:            ""
permalink:          /notes/:month-:year-:title.html # Post permalink
timezone:           France/Paris
mathjax:            false

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
  input:            GFM
sass:
  style:            :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-remote-theme
remote_theme: heiswayi/the-plain

jekyll-archives:
  enabled: ['categories']
  layout: archive
  permalinks:
    category: '/tags/:name/'

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
